/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VoiceFiPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var util = __toESM(require("util"));
var execPromise = util.promisify(import_child_process.exec);
var VOICEFI_ICON_SVG = `<path d="M 25 20 A 28 28 0 0 1 75 20" stroke="currentColor" stroke-width="6.5" stroke-linecap="round" fill="none"/>
<path d="M 34 30 A 18 18 0 0 1 66 30" stroke="currentColor" stroke-width="6" stroke-linecap="round" fill="none"/>
<path d="M 26 36 C 26 66 36 72 50 72 C 64 72 74 66 74 36" stroke="currentColor" stroke-width="5.5" stroke-linecap="round" fill="none"/>
<circle cx="39" cy="48" r="5" fill="currentColor"/>
<circle cx="61" cy="48" r="5" fill="currentColor"/>
<path d="M 39 59 Q 50 67 61 59" stroke="currentColor" stroke-width="4.5" stroke-linecap="round" fill="none"/>
<path d="M 18 44 C 18 74 30 81 50 81 C 70 81 82 74 82 44" stroke="currentColor" stroke-width="5.5" stroke-linecap="round" fill="none"/>
<line x1="50" y1="81" x2="50" y2="88" stroke="currentColor" stroke-width="6" stroke-linecap="round"/>
<line x1="36" y1="88" x2="64" y2="88" stroke="currentColor" stroke-width="6" stroke-linecap="round"/>`;
var DEFAULT_SETTINGS = {
  vifiPath: "vifi",
  audioCues: true,
  companionPort: 8765
};
var VoiceFiPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.socket = null;
    this.isListening = false;
    this.interimStart = null;
  }
  async onload() {
    await this.loadSettings();
    (0, import_obsidian.addIcon)("voicefi-logo", VOICEFI_ICON_SVG);
    this.statusBarItemEl = this.addStatusBarItem();
    this.updateStatus("Standby", "\u{1F399}\uFE0F");
    this.ribbonIconEl = this.addRibbonIcon("voicefi-logo", "VoiceFi: Toggle Active Listening", (evt) => {
      this.toggleListening();
    });
    this.addCommand({
      id: "toggle-active-listening",
      name: "Toggle Active Listening Session",
      callback: () => {
        this.toggleListening();
      }
    });
    this.addCommand({
      id: "speak-current-note",
      name: "Read Selection or Note Aloud (TTS)",
      editorCallback: async (editor, view) => {
        const text = editor.getSelection() || view.data;
        if (text.trim().length > 0) {
          this.updateStatus("Speaking...", "\u{1F50A}");
          new import_obsidian.Notice("VoiceFi: Speaking note...");
          await this.speakText(text);
          this.updateStatus(this.isListening ? "Listening..." : "Standby", this.isListening ? "\u{1F534}" : "\u{1F399}\uFE0F");
        } else {
          new import_obsidian.Notice("VoiceFi: Note or selection is empty.");
        }
      }
    });
    this.addCommand({
      id: "ask-christopher-about-note",
      name: "Ask Christopher About Active Note (Voice Q&A)",
      editorCallback: async (editor, view) => {
        const title = view.file ? view.file.basename : "";
        const content = editor.getValue() || view.data;
        new import_obsidian.Notice(`\u{1F9E0} Christopher is analyzing "${title}"...`);
        await this.askVaultAgent("Summarize this note", title, content);
      }
    });
    this.addSettingTab(new VoiceFiSettingTab(this.app, this));
  }
  updateStatus(status, icon = "\u{1F399}\uFE0F") {
    if (this.statusBarItemEl) {
      this.statusBarItemEl.setText(`${icon} VoiceFi: ${status}`);
    }
  }
  onunload() {
    this.disconnectCompanion();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  toggleListening() {
    if (this.isListening) {
      this.stopListening();
    } else {
      this.startListening();
    }
  }
  startListening() {
    if (this.isListening)
      return;
    this.isListening = true;
    this.updateIcon(true);
    this.updateStatus("Listening...", "\u{1F534}");
    new import_obsidian.Notice("VoiceFi: Active Listening Started");
    this.connectCompanion();
  }
  stopListening() {
    if (!this.isListening)
      return;
    this.isListening = false;
    this.updateIcon(false);
    this.updateStatus("Standby", "\u{1F399}\uFE0F");
    new import_obsidian.Notice("VoiceFi: Active Listening Stopped");
    this.disconnectCompanion();
  }
  updateIcon(active) {
    if (active) {
      this.ribbonIconEl.style.color = "var(--text-error)";
    } else {
      this.ribbonIconEl.style.color = "";
    }
  }
  async connectCompanion(canRetry = true) {
    if (this.socket) {
      this.socket.onopen = null;
      this.socket.onmessage = null;
      this.socket.onclose = null;
      this.socket.onerror = null;
      try {
        this.socket.close();
      } catch (e) {
      }
      this.socket = null;
    }
    try {
      const ws = new WebSocket(`ws://127.0.0.1:${this.settings.companionPort}/ws`);
      this.socket = ws;
      ws.onopen = () => {
        if (this.socket !== ws)
          return;
        console.log("VoiceFi Companion connected.");
        this.isListening = true;
        this.updateIcon(true);
        this.updateStatus("Listening...", "\u{1F534}");
        ws.send(JSON.stringify({ type: "ambient_start", source: "mic" }));
      };
      ws.onmessage = async (event) => {
        if (this.socket !== ws)
          return;
        try {
          const data = JSON.parse(event.data);
          if (data.type === "interim_transcript") {
            this.updateStatus("Typing...", "\u270D\uFE0F");
            await this.handleInterim(data.text);
          } else if (data.type === "transcript" || data.type === "ambient_utterance") {
            this.updateStatus("Listening...", "\u{1F534}");
            await this.handleTranscript(data.text);
          } else if (data.type === "ambient_energy" && data.is_speech) {
            this.updateStatus("Hearing voice...", "\u{1F5E3}\uFE0F");
          } else if (data.type === "agent_speaking_started") {
            this.updateStatus("Agent Speaking...", "\u{1F50A}");
          } else if (data.type === "agent_speaking_finished") {
            this.updateStatus("Listening...", "\u{1F534}");
          }
        } catch (e) {
          console.error("Error parsing VoiceFi message:", e);
        }
      };
      ws.onclose = () => {
        if (this.socket === ws) {
          console.log("VoiceFi Companion disconnected.");
          this.socket = null;
          if (this.isListening) {
            this.stopListening();
          }
        }
      };
      ws.onerror = async (error) => {
        if (this.socket !== ws)
          return;
        if (canRetry) {
          try {
            new import_obsidian.Notice("VoiceFi: Connecting background engine...");
            const cmd = `nohup "${this.settings.vifiPath}" companion --port ${this.settings.companionPort} --no-qr > /tmp/voicefi_companion.log 2>&1 &`;
            await execPromise(cmd);
            setTimeout(() => {
              this.connectCompanion(false);
            }, 1200);
            return;
          } catch (e) {
            console.error("Auto-start error:", e);
          }
        }
        console.error("VoiceFi WebSocket Error:", error);
        new import_obsidian.Notice("VoiceFi: Companion server unreachable.");
        this.stopListening();
      };
    } catch (e) {
      console.error(e);
      new import_obsidian.Notice("VoiceFi: Failed to connect to companion server.");
      this.stopListening();
    }
  }
  disconnectCompanion() {
    if (this.socket) {
      if (this.socket.readyState === WebSocket.OPEN) {
        try {
          this.socket.send(JSON.stringify({ type: "ambient_stop" }));
        } catch (e) {
        }
      }
      this.socket.onopen = null;
      this.socket.onmessage = null;
      this.socket.onclose = null;
      this.socket.onerror = null;
      this.socket.close();
      this.socket = null;
    }
  }
  async handleInterim(text) {
    const cleanText = text.trim();
    if (!cleanText)
      return;
    if (/^(hey\s+christopher|hey\s+voicefi|voicefi|hey\s+agent|christopher|summarize)/i.test(cleanText)) {
      this.updateStatus("Asking Christopher...", "\u{1F9E0}");
      return;
    }
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView)
      return;
    const editor = activeView.editor;
    const cursor = editor.getCursor();
    if (!this.interimStart) {
      this.interimStart = { line: cursor.line, ch: cursor.ch };
    }
    editor.replaceRange(cleanText, this.interimStart, cursor);
    editor.setCursor({
      line: this.interimStart.line,
      ch: this.interimStart.ch + cleanText.length
    });
  }
  async handleTranscript(text) {
    let cleanText = text.trim();
    if (!cleanText)
      return;
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView)
      return;
    const editor = activeView.editor;
    const cursor = editor.getCursor();
    const startPos = this.interimStart ? { ...this.interimStart } : { ...cursor };
    this.interimStart = null;
    let checkText = cleanText;
    if (/some\s+(racist|raise|race|race\s+is|eyes)/i.test(checkText)) {
      checkText = checkText.replace(/some\s+(racist|raise|race|race\s+is|eyes)/i, "summarize");
    }
    const agentMatch = checkText.match(/^(hey\s+christopher|hey\s+voicefi|voicefi|hey\s+agent|christopher)[,.:!?\s]+(.*)$/i);
    const isDirectCommand = /^(summarize(\s+this)?(\s+note)?|what\s+are\s+my\s+(tasks|action\s+items|todos)|what\s+is\s+this\s+note\s+about)[,.:!?\s]*$/i.test(checkText);
    if (agentMatch || isDirectCommand) {
      const query = agentMatch ? agentMatch[2].trim() : checkText;
      if (query.length > 0) {
        editor.replaceRange("", startPos, cursor);
        editor.setCursor(startPos);
        this.updateStatus("Thinking...", "\u{1F9E0}");
        new import_obsidian.Notice(`\u{1F9E0} VoiceFi: Asking Christopher: "${query}"...`);
        const title = activeView.file ? activeView.file.basename : "";
        const content = activeView.editor.getValue() || activeView.data;
        await this.askVaultAgent(query, title, content);
        return;
      }
    }
    let insertText = cleanText;
    const lower = cleanText.toLowerCase();
    if (lower === "new line" || lower === "newline" || lower === "new line.") {
      editor.replaceRange("\n", startPos, cursor);
      editor.setCursor({ line: startPos.line + 1, ch: 0 });
      return;
    } else if (lower === "new paragraph" || lower === "new paragraph.") {
      editor.replaceRange("\n\n", startPos, cursor);
      editor.setCursor({ line: startPos.line + 2, ch: 0 });
      return;
    } else if (lower.startsWith("bullet ") || lower.startsWith("dash ")) {
      insertText = "\n- " + cleanText.replace(/^(bullet|dash)\s+/i, "") + " ";
    } else if (lower.startsWith("task ") || lower.startsWith("todo ") || lower.startsWith("checkbox ")) {
      insertText = "\n- [ ] " + cleanText.replace(/^(task|todo|checkbox)\s+/i, "") + " ";
    } else if (lower.startsWith("heading one ") || lower.startsWith("heading 1 ")) {
      insertText = "\n# " + cleanText.replace(/^(heading one|heading 1)\s+/i, "") + "\n";
    } else if (lower.startsWith("heading two ") || lower.startsWith("heading 2 ")) {
      insertText = "\n## " + cleanText.replace(/^(heading two|heading 2)\s+/i, "") + "\n";
    } else if (lower.startsWith("heading three ") || lower.startsWith("heading 3 ")) {
      insertText = "\n### " + cleanText.replace(/^(heading three|heading 3)\s+/i, "") + "\n";
    } else {
      insertText = cleanText + " ";
    }
    editor.replaceRange(insertText, startPos, cursor);
    const lines = insertText.split("\n");
    if (lines.length > 1) {
      const lastLine = lines[lines.length - 1];
      editor.setCursor({
        line: startPos.line + lines.length - 1,
        ch: lastLine.length
      });
    } else {
      editor.setCursor({
        line: startPos.line,
        ch: startPos.ch + insertText.length
      });
    }
  }
  async askVaultAgent(query, title, content) {
    try {
      const res = await (0, import_obsidian.requestUrl)({
        url: `http://127.0.0.1:${this.settings.companionPort}/api/vault/query`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          query,
          note_title: title,
          note_content: content,
          speak: true
        })
      });
      if (res.status === 200) {
        const data = res.json;
        if (data.spoken_response) {
          new import_obsidian.Notice(`\u{1F9D4} Christopher: "${data.spoken_response}"`, 9e3);
        }
      } else {
        new import_obsidian.Notice("VoiceFi: Failed to query vault agent.");
      }
    } catch (e) {
      console.error("Vault agent error:", e);
      new import_obsidian.Notice("VoiceFi: Companion server unreachable.");
    } finally {
      if (this.isListening) {
        this.updateStatus("Listening...", "\u{1F534}");
      } else {
        this.updateStatus("Standby", "\u{1F399}\uFE0F");
      }
    }
  }
  async speakText(text) {
    try {
      const res = await (0, import_obsidian.requestUrl)({
        url: `http://127.0.0.1:${this.settings.companionPort}/api/tts`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text })
      });
      if (res.status === 200)
        return;
    } catch (e) {
    }
    try {
      const escapedText = text.replace(/"/g, '\\"');
      await execPromise(`"${this.settings.vifiPath}" speak "${escapedText}"`);
    } catch (error) {
      console.error("VoiceFi TTS Error:", error);
      new import_obsidian.Notice("VoiceFi: Failed to speak text.");
    }
  }
};
var VoiceFiSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "VoiceFi Settings" });
    new import_obsidian.Setting(containerEl).setName("CLI Path").setDesc('Path to the vifi executable (or just "vifi" if in PATH).').addText((text) => text.setPlaceholder("vifi").setValue(this.plugin.settings.vifiPath).onChange(async (value) => {
      this.plugin.settings.vifiPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Companion Port").setDesc("Port for the local VoiceFi Companion server.").addText((text) => text.setPlaceholder("8765").setValue(this.plugin.settings.companionPort.toString()).onChange(async (value) => {
      this.plugin.settings.companionPort = parseInt(value) || 8765;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Audio Cues").setDesc("Play chimes when listening starts and stops.").addToggle((toggle) => toggle.setValue(this.plugin.settings.audioCues).onChange(async (value) => {
      this.plugin.settings.audioCues = value;
      await this.plugin.saveSettings();
    }));
  }
};
